### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by mohsen1** [forms-js/discussions#1]

**Comment by kentcdodds** [comment]
I'm a big fan of something like: `forms-js` or `form-js` or `js-forms` or something like that.

**Comment by kentcdodds** [comment]
Then adapters would be something like `forms-js-angular` and `forms-js-react` etc.

**Comment by mchapman** [comment]
Was thinking along the same lines, also thought of making it a bit more "producty" - jforms / J-Form or similar

**Comment by bvaughn** [comment]
+1 for `forms-js` or `js-forms`.

Should not be the biggest deciding factor, but jsforms.org is available.

**Comment by mohsen1** [comment]
+1 for `js-forms` or `forms-js`

**Comment by davidlgj** [comment]
+1 for `forms-js`, thats my favourite, but `js-forms` works as well.

**Comment by mohsen1** [comment]
`forms-js.{com,org,net}` is available. So let's go with that.

Renaming the repo

**Comment by bvaughn** [comment]
Sounds great. I've snagged those domains for now so we'll have them.

**Comment by mohsen1** [comment]
Thank you for domain! @bvaughn
